//## Copyright (c) 2017-2019 The Khronos Group Inc.
//## Copyright (c) 2019 Collabora, Ltd.
//##
//## Licensed under the Apache License, Version 2.0 (the "License");
//## you may not use this file except in compliance with the License.
//## You may obtain a copy of the License at
//##
//##     http://www.apache.org/licenses/LICENSE-2.0
//##
//## Unless required by applicable law or agreed to in writing, software
//## distributed under the License is distributed on an "AS IS" BASIS,
//## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//## See the License for the specific language governing permissions and
//## limitations under the License.
//##
//## ---- Exceptions to the Apache 2.0 License: ----
//##
//## As an exception, if you use this Software to generate code and portions of
//## this Software are embedded into the generated code as a result, you may
//## redistribute such product without providing attribution as would otherwise
//## be required by Sections 4(a), 4(b) and 4(d) of the License.
//##
//## In addition, if you combine or link code generated by this Software with
//## software that is licensed under the GPLv2 or the LGPL v2.0 or 2.1
//## ("`Combined Software`") and if a court of competent jurisdiction determines
//## that the patent provision (Section 3), the indemnity provision (Section 9)
//## or other Section of the License conflicts with the conditions of the
//## applicable GPL or LGPL license, you may retroactively and prospectively
//## choose to deem waived or otherwise exclude such Section(s) of the License,
//## but only in their entirety and only with respect to the Combined Software.



#include <openxr/openxr.h>
#include <openxr/openxr_platform.h>

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstring>
#include <initializer_list>
#include <string>
#include <system_error>
#include <tuple>
#include <type_traits>

#ifndef OPENXR_HPP_DISABLE_ENHANCED_MODE
#include <memory>
#include <vector>
#endif /*OPENXR_HPP_DISABLE_ENHANCED_MODE*/

/*% include('template_preproc.hpp') %*/

/*!
 * @brief Namespace containing all openxr.hpp entities.
 *
 * If the default namespace `xr` isn't suitable, you can define OPENXR_HPP_NAMESPACE to a different name before including this
 * header.
 */
namespace OPENXR_HPP_NAMESPACE {
// Forward declaration
class DispatchLoaderDynamic;

// The generalization of std::string with user-specifiable allocator types.
template <typename Allocator = std::allocator<char>>
using string_with_allocator = std::basic_string<char, std::char_traits<char>, Allocator>;

using Bool32 = XrBool32;

enum Side : uint32_t {
    Left = 0,
    Right = 1,
};

constexpr uint32_t SIDE_COUNT = 2;

constexpr char const* const reserved_paths[] = {
    "/user/hand/left", "/user/hand/right", "/user/head", "/user/gamepad", "/user/treadmill",
};

constexpr char const* const interaction_profiles[] = {
    "/interaction_profiles/khr/simple_controller",       "/interaction_profiles/google/daydream_controller",
    "/interaction_profiles/htc/vive_controller",         "/interaction_profiles/htc/vive_pro",
    "/interaction_profiles/microsoft/motion_controller", "/interaction_profiles/microsoft/xbox_controller",
    "/interaction_profiles/oculus/go_controller",        "/interaction_profiles/oculus/touch_controller",
    "/interaction_profiles/valve/index_controller",
};

template <typename SideHandler>
static inline void for_each_side(SideHandler&& handler) {
    handler(Left);
    handler(Right);
}

template <typename IndexHandler>
static inline void for_each_side_index(IndexHandler&& handler) {
    handler(0);
    handler(1);
}

}  // namespace OPENXR_HPP_NAMESPACE
