//## Copyright (c) 2017-2019 The Khronos Group Inc.
//## Copyright (c) 2019 Collabora, Ltd.
//##
//## Licensed under the Apache License, Version 2.0 (the "License");
//## you may not use this file except in compliance with the License.
//## You may obtain a copy of the License at
//##
//##     http://www.apache.org/licenses/LICENSE-2.0
//##
//## Unless required by applicable law or agreed to in writing, software
//## distributed under the License is distributed on an "AS IS" BASIS,
//## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//## See the License for the specific language governing permissions and
//## limitations under the License.
//##
//## ---- Exceptions to the Apache 2.0 License: ----
//##
//## As an exception, if you use this Software to generate code and portions of
//## this Software are embedded into the generated code as a result, you may
//## redistribute such product without providing attribution as would otherwise
//## be required by Sections 4(a), 4(b) and 4(d) of the License.
//##
//## In addition, if you combine or link code generated by this Software with
//## software that is licensed under the GPLv2 or the LGPL v2.0 or 2.1
//## ("`Combined Software`") and if a court of competent jurisdiction determines
//## that the patent provision (Section 3), the indemnity provision (Section 9)
//## or other Section of the License conflicts with the conditions of the
//## applicable GPL or LGPL license, you may retroactively and prospectively
//## choose to deem waived or otherwise exclude such Section(s) of the License,
//## but only in their entirety and only with respect to the Combined Software.

//# include('copyright_header.hpp') without context

//# from 'macros.hpp' import include_guard_begin, include_guard_end
/*{ include_guard_begin() }*/

/**
 * @file
 * @brief Forward declarations of OpenXR handle wrapper types.
 *
 * @see openxr_handles.hpp
 */

#include "openxr_enums.hpp"

//# include('define_namespace.hpp') without context
//# include('nongenerated_unique.hpp') without context

namespace OPENXR_HPP_NAMESPACE {

//! Type traits
namespace traits {
    //! Type trait associating an ObjectType enum value with its C++ type.
    template <ObjectType o>
    struct cpp_type;
}  // namespace traits

// forward declarations

class DispatchLoaderStatic;
class DispatchLoaderDynamic;

//# for handle in gen.api_handles
class /*{ project_type_name(handle.name) }*/;
//# endfor

/*!
 * @defgroup handles Handle types
 * @brief Wrappers for OpenXR handle types, with associated functions mapped as methods.
 * @{
 */
/*!
 * @defgroup unique_handle_aliases Aliases for UniqueHandle types
 * @brief Convenience names for specializations of UniqueHandle<>
 */
//! @}

//# for handle in gen.api_handles
//#     set shortname = project_type_name(handle.name)

#ifndef OPENXR_HPP_NO_SMART_HANDLE

namespace traits {
//! Traits associating a deleter type with handles of type /*{shortname}*/
template <typename Dispatch>
class UniqueHandleTraits</*{shortname}*/, Dispatch> {
   public:
    using deleter = ObjectDestroy<Dispatch>;
};
} //namespace traits

//! @addtogroup unique_handle_aliases
//! @{

//## TODO use DispatchLoaderDynamic for extension-provided handles!
//! Shorthand name for unique handles of type /*{shortname}*/, using a static dispatch.
using /*{'Unique' + shortname}*/ = UniqueHandle</*{shortname}*/, DispatchLoaderStatic>;
//! Shorthand name for unique handles of type /*{shortname}*/, using a dynamic dispatch.
using /*{'UniqueDynamic' + shortname}*/ = UniqueHandle</*{shortname}*/, DispatchLoaderDynamic>;
//! @}
#endif /*OPENXR_HPP_NO_SMART_HANDLE*/

namespace traits {
//! @brief Explicit specialization of cpp_type for /*{shortname}*/
template <>
struct cpp_type<ObjectType::/*{shortname}*/> {
    using type = /*{shortname}*/;
};
} // namespace traits

//# endfor

}  // namespace OPENXR_HPP_NAMESPACE

/*{ include_guard_end() }*/
