//## Copyright (c) 2017-2020 The Khronos Group Inc.
//## Copyright (c) 2019-2020 Collabora, Ltd.
//##
//## Licensed under the Apache License, Version 2.0 (the "License");
//## you may not use this file except in compliance with the License.
//## You may obtain a copy of the License at
//##
//##     http://www.apache.org/licenses/LICENSE-2.0
//##
//## Unless required by applicable law or agreed to in writing, software
//## distributed under the License is distributed on an "AS IS" BASIS,
//## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//## See the License for the specific language governing permissions and
//## limitations under the License.
//##
//## ---- Exceptions to the Apache 2.0 License: ----
//##
//## As an exception, if you use this Software to generate code and portions of
//## this Software are embedded into the generated code as a result, you may
//## redistribute such product without providing attribution as would otherwise
//## be required by Sections 4(a), 4(b) and 4(d) of the License.
//##
//## In addition, if you combine or link code generated by this Software with
//## software that is licensed under the GPLv2 or the LGPL v2.0 or 2.1
//## ("`Combined Software`") and if a court of competent jurisdiction determines
//## that the patent provision (Section 3), the indemnity provision (Section 9)
//## or other Section of the License conflicts with the conditions of the
//## applicable GPL or LGPL license, you may retroactively and prospectively
//## choose to deem waived or otherwise exclude such Section(s) of the License,
//## but only in their entirety and only with respect to the Combined Software.

//# from 'macros.hpp' import make_spec_ref

//# set type = "Version"
//# set comparison_operators = ('<', '>', '<=', '>=', '==', '!=')
//# set invalid = ""
//# set filename = "openxr_version"
//# set doc_group = "wrappers"
//# extends "valuewrapperclass_header.hpp"

//# block includes
/**
 * @file
 * @brief Contains a type-safe C++ projection of the OpenXR packed version type.
 * @ingroup wrappers
 */

#include <openxr/openxr.h>

#ifdef OPENXR_HPP_DOXYGEN
#include <openxr/openxr_platform.h>
#endif
//# endblock

//## Add component-wise constructor
//# block extra_constructors_conversion_assign

//! Constructor from version components
Version(uint16_t major_, uint16_t minor_, uint32_t patch_) noexcept {
    major(major_);
    minor(minor_);
    patch(patch_);
}

//# endblock extra_constructors_conversion_assign

//## No validity methods
//# block validity
//# endblock

//# block extra_methods
//# filter block_doxygen_comment
//! @brief Get the major component.
//!
//! /*{ make_spec_ref("XR_VERSION_MAJOR") }*/
//!
//! @xrentity{XR_VERSION_MAJOR}
//# endfilter
OPENXR_HPP_CONSTEXPR uint16_t major() const noexcept
{
    return static_cast<uint16_t>(val_ >> 48);
}

//! Set the major component: 16 bits.
void major(uint16_t val) noexcept
{
    // blank the top 16 bits
    val_ &= 0x0000ffffffffffff;
    val_ |= uint64_t(val) << 48;
}


//# filter block_doxygen_comment
//! @brief Get the minor component.
//!
//! /*{ make_spec_ref("XR_VERSION_MINOR") }*/
//!
//! @xrentity{XR_VERSION_MINOR}
//# endfilter
OPENXR_HPP_CONSTEXPR uint16_t minor() const noexcept
{
    return static_cast<uint16_t>((val_ >> 32) & 0xffff);
}
//! Set the minor component: 16 bits.
void minor(uint16_t val) noexcept
{
    // blank the correct 16 bits
    val_ &= 0xffff0000ffffffff;
    val_ |= uint64_t(val) << 32;
}

//# filter block_doxygen_comment
//! @brief Get the patch component.
//!
//! /*{ make_spec_ref("XR_VERSION_PATCH") }*/
//!
//! @xrentity{XR_VERSION_PATCH}
//# endfilter
OPENXR_HPP_CONSTEXPR uint32_t patch() const noexcept
{
    return static_cast<uint32_t>(val_ & 0xffffffff);
}
//! Set the patch component: 32 bits.
void patch(uint32_t val) noexcept
{
    // blank the least-significant 32 bits
    val_ &= 0xffffffff00000000;
    val_ |= val;
}


//# filter block_doxygen_comment
//! @brief Get the current version of OpenXR, based on the header.
//!
//! /*{ make_spec_ref("XR_CURRENT_API_VERSION") }*/
//!
//! @xrentity{XR_CURRENT_API_VERSION}
//# endfilter
static OPENXR_HPP_CONSTEXPR Version current() noexcept
{
    return Version{XR_CURRENT_API_VERSION};
}
//# endblock
